import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import {
  ImageLazyLoadDirective,
  SwitchComponent,
  QRCodeComponent,
  PhoneValidator,
  PasswordValidator,
  PositiveValidator,
  PositiveIntegerValidator,
  SameValidator,
  EmailValidator,
  UrlValidator,
  MinValidator,
  MaxValidator,
  RegExpValidator,
  MyRequiredValidator,
  ImageUploadComponent,
  EditorComponent,
  UiLoadingComponent,
  PaginationComponent,
  WizardHorizontalComponent,
  SelectComponent,
  BtnSavingDirective,
  TouchFormDirective,
  DivMoveDirective,
  EscDirective,
  CalendarComponent,
  TimeComponent,
  TimepickerComponent,
  SliderComponent,
  ProgressComponent,
  AvatarComponent,
  RateComponent
} from 'le5le-components';

import { HtmlPipe } from './pipes/html.pipe';

@NgModule({
  imports: [CommonModule, FormsModule, RouterModule, ReactiveFormsModule],
  declarations: [
    HtmlPipe,
    ImageLazyLoadDirective,
    SwitchComponent,
    QRCodeComponent,
    PhoneValidator,
    PasswordValidator,
    PositiveValidator,
    PositiveIntegerValidator,
    SameValidator,
    EmailValidator,
    UrlValidator,
    MinValidator,
    MaxValidator,
    RegExpValidator,
    MyRequiredValidator,
    ImageUploadComponent,
    EditorComponent,
    UiLoadingComponent,
    PaginationComponent,
    WizardHorizontalComponent,
    SelectComponent,
    BtnSavingDirective,
    TouchFormDirective,
    DivMoveDirective,
    EscDirective,
    CalendarComponent,
    TimeComponent,
    TimepickerComponent,
    SliderComponent,
    ProgressComponent,
    AvatarComponent,
    RateComponent
  ],
  exports: [
    CommonModule,
    FormsModule,
    RouterModule,
    ReactiveFormsModule,
    HtmlPipe,
    ImageLazyLoadDirective,
    SwitchComponent,
    QRCodeComponent,
    PhoneValidator,
    PasswordValidator,
    PositiveValidator,
    PositiveIntegerValidator,
    SameValidator,
    EmailValidator,
    UrlValidator,
    MinValidator,
    MaxValidator,
    RegExpValidator,
    MyRequiredValidator,
    ImageUploadComponent,
    EditorComponent,
    UiLoadingComponent,
    PaginationComponent,
    WizardHorizontalComponent,
    SelectComponent,
    BtnSavingDirective,
    TouchFormDirective,
    DivMoveDirective,
    EscDirective,
    CalendarComponent,
    TimeComponent,
    TimepickerComponent,
    SliderComponent,
    ProgressComponent,
    AvatarComponent,
    RateComponent
  ],
  providers: []
})
export class SharedModule {}
